### ISSUE TITLE
[BUG - Release 0.5.1]

### ISSUE THREAD

**Issue by TonicSpirits** [WistfulHopes/RE-UE4SS#2]
**Branch or Release**
Release 0.5.1

**Game and Engine Version**
Guilty Gear Strive

**Describe the bug**
Using keyboard controls, the game stutters in-menu and in gameplay when pressing the "J" key. Most of the time the "J" input will come through after the stutter, but it sometimes doesn't. For some reason, the stutter will not happen if the "D" key is held down while the "J" key is pressed.

I haven't tested it with alternate controllers like DualShock 4 or Hitbox, and I'm not certain if it's the "J" key causing problems or if it's just a coincidence with my machine. But when I swap binds in Strive with my "J" key, the new button bound to "J" will cause stutters.
e.g. If I have "J" bound to Punch and "K" bound to Kick, pressing Punch causes stutters. If I swap those binds, pressing Kick causes stutters.

**To Reproduce**
1. Extract contents from UE4SS_StriveHitboxes.zip into file path: ...\Steam\steamapps\common\GUILTY GEAR STRIVE\RED\Binaries\Win64
2. Define ModsFolderPath in UE4SS-settings.ini as: ModsFolderPath = C:\Program Files (x86)\Steam\steamapps\common\GUILTY GEAR STRIVE\RED\Binaries\Win64\Mods
3. Extract contents of Strive Hitboxes.rar into file path: C:\Program Files (x86)\Steam\steamapps\common\GUILTY GEAR STRIVE\RED\Content\Paks
4. Launch the game, and press the "J" key at any point during menu-browsing or gameplay.

**Screenshots and UE4SS Log**
https://twitter.com/TonicSpirits/status/1649960832560922625?s=20
- Examples of stuttering when pressing Punch, bound to "J" key

https://twitter.com/TonicSpirits/status/1649961022781009920?s=20
- Example of stuttering not happening when "D" (bound to Left) is held down. 22P causes stutters, whereas 214P does not.

https://twitter.com/TonicSpirits/status/1649967317227536390?s=20
- More examples of stutters (or lack thereof), with sideswitches shown. Tested with alternate keybinds for directions, and stutters consistently did _not_ happen whenever the "D" key was held down.

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by WistfulHopes** [comment]
_should_ be fixed with 0.6

**Comment by TonicSpirits** [comment]
![image](https://user-images.githubusercontent.com/96750845/233891015-83ab5675-ba3c-4e4f-9525-c32a753f465c.png)
Got the following error message:
sigscan failed!

![image](https://user-images.githubusercontent.com/96750845/233891068-b4381fc1-35ef-4ba1-a8fb-9d3e4039c134.png)
Strive still opens, and this window, which I'm guessing is the Debug console, opens as well.

When loading into Strive, the hitbox and frame advantage mod is not active.

**Comment by WistfulHopes** [comment]
there was a critical bug in 0.6 that prevented the mod from loading under 99% of circumstances

**Comment by TonicSpirits** [comment]
Still getting the sigscan failed error
![image](https://user-images.githubusercontent.com/96750845/234137982-e6cc0388-8de8-4695-b3d9-84d0356a1719.png)

If it might help diagnose, I included the UE4SS.log file that generated when booting the game.
[UE4SS.log](https://github.com/WistfulHopes/RE-UE4SS/files/11315317/UE4SS.log)
